version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
     - .:/app
     - /app/node_modules
    ports:
      - "3000:3000"
    links:
      - db
